version: '3.9'

services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=supergo
    volumes:
      - ./mongo-local/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./db-data:/data/db

  supergo-api:
    image: supergo-api
    container_name: supergo-api
    restart: always
    ports:
      - '8080:8080'
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ENVIRONMENT=local
    depends_on:
      - mongodb